Dev
HenryTabima/enumerable_methods pull request #1
Opened 2019-03-29 21:55 UTC by HenryTabima

My own version of enumerable methods with test cases as comments

2019-03-29 23:59 UTC, zlayabekrija requested changes
This was a great showcase of your skills great work 👏, yet my major concern here is that your methods were built on top of another, please fix this stuff, I am sure it's going to be a piece of 🍰 for you, submit the new review request and there you go..
Happy coding 😄

2019-03-29 23:59 UTC, zlayabekrija commented on main.rb
> +    my_inject(true) { |res, i| res && yield(i) }
Please don't reuse the method that is returning a value.

2019-03-29 23:59 UTC, zlayabekrija commented on main.rb
> +    my_inject(false) { |res, i| res || yield(i) }
Same here, it's obvious that you understand the way everything works, which is great, yet methods shouldn't rely on top of another.

2019-03-29 23:59 UTC, zlayabekrija commented on main.rb
> +    !my_any? { |i| yield(i) }
What would happen if you delete the my_any? method, my_none wouldn't work either.

2019-04-01 18:08 UTC, zlayabekrija approved these changes
Great work, great understanding. Thumbs up 👍 . Good luck with the next projects, and happy coding.

2019-04-01 18:31 UTC, HenryTabima commented
Thanks! :+1:

2019-04-01 18:31 UTC, merged